import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@/styles/global.css';
import { Toaster } from 'react-hot-toast';
import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
import Header from '@/components/Header/Header';
import AuthProvider from './(auth routes)/AuthProvider';
import Footer from '@/components/Footer/Footer';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Relax Map',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
   modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <TanStackProvider>
          <AuthProvider>
            <div className="appLayout">
              <Header />

              <main className="appContent">{children}</main>

              <Footer />
            </div>

            <Toaster position="bottom-center" />
            {modal}
          </AuthProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}
